# Generated by Django 5.1.4 on 2024-12-10 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('is_secure', models.BooleanField(default=True)),
                ('responsible_staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('maintenance', 'In Maintenance'), ('transit', 'In Transit'), ('reserved', 'Reserved')], max_length=20)),
                ('parking_spot', models.CharField(max_length=50)),
                ('arrival_date', models.DateField()),
                ('last_moved', models.DateTimeField(auto_now=True)),
                ('assigned_sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_number', models.CharField(max_length=50, unique=True)),
                ('key_type', models.CharField(choices=[('main', 'Main Key'), ('spare', 'Spare Key'), ('valet', 'Valet Key')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('last_inventory_check', models.DateTimeField(null=True)),
                ('current_storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keys.keystorage')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keys.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Yard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_yards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_yard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_vehicles', to='keys.yard'),
        ),
        migrations.AddField(
            model_name='keystorage',
            name='yard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keys.yard'),
        ),
        migrations.CreateModel(
            name='KeyCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_time', models.DateTimeField()),
                ('actual_return_time', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost')], max_length=20)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_authorizations', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_checkouts', to=settings.AUTH_USER_MODEL)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keys.key')),
                ('checkout_yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_checkouts', to='keys.yard')),
                ('return_yard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_returns', to='keys.yard')),
            ],
        ),
        migrations.CreateModel(
            name='YardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.IntegerField()),
                ('yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='keys.yard')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='yard_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keys.yardsection'),
        ),
    ]
