# Generated by Django 5.1.4 on 2024-12-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='yard_section',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='parking_spot',
            field=models.CharField(help_text="Location within the yard (e.g., 'A-12', 'Back Lot 5')", max_length=50),
        ),
        migrations.DeleteModel(
            name='YardSection',
        ),
    ]
