# Generated by Django 5.1.4 on 2024-12-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0004_vehicle_number_plate_alter_vehicle_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycheckout',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
