# Generated by Django 5.1.4 on 2024-12-10 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0008_alter_vehicle_parking_spot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycheckout',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keycheckout',
            name='purpose',
            field=models.CharField(default='aaa', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keycheckout',
            name='return_yard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_returns', to='keys.yard'),
        ),
        migrations.AlterField(
            model_name='keycheckout',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('lost', 'Lost')], default='active', max_length=20),
        ),
    ]
